### ISSUE TITLE
Error: pull-reader: read exceeded timeout

### ISSUE THREAD

**Issue by staltz** [ssbc/ssb-tunnel#5]
I've been struggling to get a simple test running for two clients and one portal, I keep hitting the error:

```
node_modules/ssb-server/node_modules/muxrpc/api.js:14
  if (err) throw explain(err, 'callback not provided')
           ^

Error: callback not provided
    at noop (node_modules/ssb-server/node_modules/muxrpc/api.js:14:18)
    at node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:18:14
    at node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:10:5
    at node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:59:17
    at node_modules/ssb-server/node_modules/pull-stream/sinks/drain.js:20:24
    at PacketStreamSubstream.weird.read (node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (node_modules/ssb-server/node_modules/packet-stream/index.js:224:13)
    at PacketStream.write (node_modules/ssb-server/node_modules/packet-stream/index.js:135:41)
    at node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:56:15
  Error: pull-reader: read exceeded timeout
    at Timeout._onTimeout (/data/data/se.manyver/files/nodejs-project/index.js:53114:10)
    at ontimeout (timers.js:437:11)
    at tryOnTimeout (timers.js:301:5)
    at listOnTimeout (timers.js:264:5)
    at Timer.processTimers (timers.js:224:10)
```

on both portal and clients. All three crash, at almost the same time (plus or minus 2 seconds). **Is there anything obvious I'm missing here?** Here's my setup:

--------

- **Portal `@3uQd...`** running a [simple fork of ssb-tunnel](https://github.com/staltz/ssb-room/blob/5b09c5c7cd40cd480f465aa32e78ebc242ff3bdf/tunnel.js)
- **Client `@Dyora...`** running a fork of ssb-tunnel that I haven't published yet, called "room-client"
- **Client `@Mhxnwib...`** (similar to the one above)

### Portal `@3uQd...` logs

```
19:47:12.968Z multiserver:net Listening on 0.0.0.0:8008
19:47:12.984Z ssb:conn-db Loaded conn.json into ConnDB in memory
19:47:27.607Z ssb:conn-hub RPC client @Dyora4YFZeLAo1DYx4VWbUmMpMoTDg1adm/5siXxVQQ=.ed25519 connected to us, but not via conn-hub
19:47:27      ssb:room:tunnel received endpoint announcement from: @Dyora4YFZeLAo1DYx4VWbUmMpMoTDg1adm/5siXxVQQ=.ed25519
19:48:00.347Z ssb:conn-hub RPC client @Mhxnwib9J7WE/b9V44dJQIx3uTMl8eK6knb/ZQwaCp4=.ed25519 connected to us, but not via conn-hub
19:48:00      ssb:room:tunnel received endpoint announcement from: @Mhxnwib9J7WE/b9V44dJQIx3uTMl8eK6knb/ZQwaCp4=.ed25519
19:48:02      ssb:room:tunnel received tunnel request for target @Dyora4YFZeLAo1DYx4VWbUmMpMoTDg1adm/5siXxVQQ=.ed25519 from @Mhxnwib9J7WE/b9V44dJQIx3uTMl8eK6knb/ZQwaCp4=.ed25519
/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-server/node_modules/muxrpc/api.js:14
  if (err) throw explain(err, 'callback not provided')
           ^

Error: callback not provided
    at noop (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-server/node_modules/muxrpc/api.js:14:18)
    at /home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:18:14
    at /home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:10:5
    at /home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:59:17
    at /home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-server/node_modules/pull-stream/sinks/drain.js:20:24
    at PacketStreamSubstream.weird.read (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:33:7)
    at PacketStream._onstream (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-server/node_modules/packet-stream/index.js:224:13)
    at PacketStream.write (/home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-server/node_modules/packet-stream/index.js:135:41)
    at /home/node/.npm-global/lib/node_modules/ssb-room/node_modules/ssb-server/node_modules/muxrpc/pull-weird.js:56:15
  Error: pull-reader: read exceeded timeout
    at Timeout._onTimeout (/data/data/se.manyver/files/nodejs-project/index.js:53114:10)
    at ontimeout (timers.js:437:11)
    at tryOnTimeout (timers.js:301:5)
    at listOnTimeout (timers.js:264:5)
    at Timer.processTimers (timers.js:224:10)
```

### Client `@Dyora...` logs

```
19:47:26.713 multiserver:net Listening on 192.168.43.252:26831
19:47:27.098 ssb:conn-db Loaded conn.json into ConnDB in memory
19:47:27.579 ssb:conn-hub connecting to net:165.22.204.212:8008~shs:3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=
19:47:27.637 ssb:conn-hub disconnecting from net:165.22.204.212:8008~shs:3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=
19:47:27.640 ssb:conn-hub disconnected from net:165.22.204.212:8008~shs:3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=
19:47:27.924 ssb:conn-hub connected to net:165.22.204.212:8008~shs:3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=
19:47:27.928 room-client will try to call tunnel.endpoints() at new gossip peer: @3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519
19:47:28.101 ssb:conn-hub connected to net:165.22.204.212:8008~shs:3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=
19:47:28.104 room-client will try to call tunnel.endpoints() at new gossip peer: @3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519
19:47:28.145 room-client got endpoints from @3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519: []
19:47:28.147 room-client server setupPortal(@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519)
19:47:28.149 room-client server setting up handler for @3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519
19:47:28.171 room-client server announcing to portal:@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519
19:47:28.215 room-client got endpoints from @3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519: []
19:47:28.215 room-client server WOULD redundantly setupPortal(@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519) but cancelled that
19:47:28.267 room-client server - SUCCESS establishing portal:@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519
19:48:02.998 room-client received incoming connect({"target":"@Dyora4YFZeLAo1DYx4VWbUmMpMoTDg1adm/5siXxVQQ=.ed25519","portal":"@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519"})
19:48:03.008 room-client connect() will resolve because handler exists
19:48:03.013 room-client server HANDLER will call onConnect for the stream.address: tunnel:@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519:@Dyora4YFZeLAo1DYx4VWbUmMpMoTDg1adm/5siXxVQQ=.ed25519
19:48:07.934 server error, from tunnel:@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519:@Dyora4YFZeLAo1DYx4VWbUmMpMoTDg1adm/5siXxVQQ=.ed25519~shs:
19:48:07.934 Error: pull-reader: read exceeded timeout
19:48:07.934     at Timeout._onTimeout (/data/data/se.manyver/files/nodejs-project/index.js:53114:10)
19:48:07.934     at ontimeout (timers.js:437:11)
19:48:07.934     at tryOnTimeout (timers.js:301:5)
19:48:07.934     at listOnTimeout (timers.js:264:5)
19:48:07.934     at Timer.processTimers (timers.js:224:10)
19:48:07.951 ssb:conn-hub disconnected from net:165.22.204.212:8008~shs:3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=
```

### Client `@Mhxnwib...` logs

```
19:47:43.997 multiserver:net Listening on 192.168.1.100:26831
19:47:44.193 ssb:conn-db Loaded conn.json into ConnDB in memory
19:48:01.141 ssb:conn-hub connecting to net:165.22.204.212:8008~shs:3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=
19:48:01.316 ssb:conn-hub connected to net:165.22.204.212:8008~shs:3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=
19:48:01.319 room-client will try to call tunnel.endpoints() at new gossip peer: @3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519
19:48:01.437 room-client got endpoints from @3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519: [{"id":"@Dyora4YFZeLAo1DYx4VWbUmMpMoTDg1adm/5siXxVQQ=.ed25519","address":"tunnel:@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519:@Dyora4YFZeLAo1DYx4VWbUmMpMoTDg1adm/5siXxVQQ=.ed25519"}]
19:48:01.438 room-client server setupPortal(@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519)
19:48:01.441 room-client server setting up handler for @3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519
19:48:01.462 room-client server announcing to portal:@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519
19:48:01.535 room-client server - SUCCESS establishing portal:@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519
19:48:03.443 room-client will gossip.connect(tunnel:@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519:@Dyora4YFZeLAo1DYx4VWbUmMpMoTDg1adm/5siXxVQQ=.ed25519)
19:48:03.495 ssb:conn-hub connecting to tunnel:@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519:@Dyora4YFZeLAo1DYx4VWbUmMpMoTDg1adm/5siXxVQQ=.ed25519
19:48:03.507 room-client client will retrieve portal peer:@3uQdTntgfgUZKEMlWsKerARTUxQjSWQuaxu/BtnZsaw=.ed25519
19:48:03.507 room-client client has portal connected, will tunnel to target:@Dyora4YFZeLAo1DYx4VWbUmMpMoTDg1adm/5siXxVQQ=.ed25519
19:48:08.827 Error: callback not provided
19:48:08.827     at noop (/data/data/se.manyver/files/nodejs-project/index.js:58808:18)
19:48:08.827     at /data/data/se.manyver/files/nodejs-project/index.js:88100:14
19:48:08.827     at /data/data/se.manyver/files/nodejs-project/index.js:88092:5
19:48:08.827     at source (/data/data/se.manyver/files/nodejs-project/index.js:88126:20)
19:48:08.827     at Function.reader.abort (/data/data/se.manyver/files/nodejs-project/index.js:53183:7)
19:48:08.827     at Object.abort (/data/data/se.manyver/files/nodejs-project/index.js:23219:16)
19:48:08.827     at abort (/data/data/se.manyver/files/nodejs-project/index.js:84421:39)
19:48:08.827     at Object.cb (/data/data/se.manyver/files/nodejs-project/index.js:84426:24)
19:48:08.827     at drain (/data/data/se.manyver/files/nodejs-project/index.js:53144:23)
19:48:08.827   Error: pull-reader: read exceeded timeout
19:48:08.827     at Timeout._onTimeout (/data/data/se.manyver/files/nodejs-project/index.js:53114:10)
19:48:08.827     at ontimeout (timers.js:437:11)
19:48:08.827     at tryOnTimeout (timers.js:301:5)
19:48:08.827     at listOnTimeout (timers.js:264:5)
19:48:08.827     at Timer.processTimers (timers.js:224:10)
```

**Comment by staltz** [comment]
Nevermind, I forgot to add `~shs:_____` in the tunnel addresses!
